name: deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login-docker
      run: docker login --username ${{ secrets.DOCKER_HUB_USER_NAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build, test tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ secrets.DOCKER_HUB_USER_NAME }}
        REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Logout of Docker Hub
      if: always()
      run: docker logout

